language: node_js
os:
  - windows
  - osx
addons:
  chrome: stable
  firefox: latest
branches:
  only:
    - master
jobs:
  include:
    - stage: tests
      node_js:
        - "10"
      os: osx
      script:
        - npm run test:coverage
        - codecov
    - stage: tests
      node_js:
        - "10"
      os: windows
      script:
        - npm run test:coverage
        - codecov
